### ISSUE TITLE
Purchase-order

### ISSUE THREAD

**Issue by diegolirio** [diegolirio/kotlin-spring-boot#5]
### Tasks

- [X]  Creating app purchase-order
- [X]  Creating app purchase-order-process
- [ ]  Creating api POST /buy and save in the MongoDB

**Comment by ddamacena** [comment]
FROM gradle:jdk21-alpine
LABEL maintainer="l-investimento-nova-iorque"
EXPOSE 8080
#RUN useradd -r userapp
ARG PROJECT_NAME_MODULE
ADD $PROJECT_NAME_MODULE/build/libs/app.jar /app.jar
#RUN chown -R userapp app.jar
ENTRYPOINT java $JAVA_OPTS -jar /app.jar
#USER userapp

**Comment by ddamacena** [comment]
FROM gradle:jdk21-alpine
